export const PRE_SET_LIST = [
    {
        btnLabel: "Data no erros",
        eventData: {
            eventName: "Climate Strike",
            eventNameType: "string",
            eventImgUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Greta_Thunberg_4.jpg/250px-Greta_Thunberg_4.jpg",
            eventImgUrlType: "string",
            eventDate: 1588723200000,
            eventDateType: "int",
            eventPrice: "0",
            eventPriceType: "string",
            eventDescription: "Strike for the climate",
            eventDescriptionType: "string",
            eventTags: "#gretaRules",
            eventTagsType: "string",
            eventTickets: "1000",
            eventTicketsType: "string",
            showBar: true,
        }
    },
    {
        btnLabel: "Data no erros",
        eventData: {
            eventName: "Corona quarantine",
            eventNameType: "string",
            eventImgUrl: "https://www.statnews.com/wp-content/uploads/2020/02/Coronavirus-CDC.jpg",
            eventImgUrlType: "string",
            eventDate: 1585180800000,
            eventDateType: "int",
            eventPrice: "500000",
            eventPriceType: "string",
            eventDescription: "Corona quarantine at you place. Everyone stays inside their home and interact with other people through the internet.",
            eventDescriptionType: "string",
            eventTags: "#selfQuarantine, #staySafe",
            eventTagsType: "string",
            eventTickets: "3",
            eventTicketsType: "string",
            showBar: true,
        }
    },
    {
        btnLabel: "Data with int error",
        eventData: {
            eventName: 1,
            eventNameType: "int",
            eventImgUrl: "https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg",
            eventImgUrlType: "string",
            eventDate: 1591401600000,
            eventDateType: "int",
            eventPrice: "0",
            eventPriceType: "string",
            eventDescription: "Celebrate Sweden's national day",
            eventDescriptionType: "string",
            eventTags: "#hurray",
            eventTagsType: "string",
            eventTickets: "10000000",
            eventTicketsType: "string",
            showBar: true,
        }
    },
    {
        btnLabel: "Data with tag and ticket error",
        eventData: {
            eventName: "Football game",
            eventNameType: "string",
            eventImgUrl: "https://images-na.ssl-images-amazon.com/images/I/61F-Epj6A9L._SX355_.jpg",
            eventImgUrlType: "string",
            eventDate: 1596240000000,
            eventDateType: "int",
            eventPrice: "0",
            eventPriceType: "string",
            eventDescription: "Fotboll game",
            eventDescriptionType: "string",
            eventTags: "#football zlatan",
            eventTagsType: "string",
            eventTickets: "0",
            eventTicketsType: "string",
            showBar: true,
        }
    },
    {
        btnLabel: "Data with tag error",
        eventData: {
            eventName: "Mario Cart",
            eventNameType: "string",
            eventImgUrl: "https://upload.wikimedia.org/wikipedia/en/a/a9/MarioNSMBUDeluxe.png",
            eventImgUrlType: "string",
            eventDate: 1591401600000,
            eventDateType: "int",
            eventPrice: "100",
            eventPriceType: "string",
            eventDescription: "Play Mario Cart together",
            eventDescriptionType: "string",
            eventTags: "#mario #marioCart #luigi #cars #competition",
            eventTagsType: "string",
            eventTickets: "10",
            eventTicketsType: "string",
            showBar: true,
        }
    },
    {
        btnLabel: "Data with null error",
        eventData: {
            eventName: "Sun eclipse",
            eventNameType: "string",
            eventImgUrl: "https://solarsystem.nasa.gov/system/basic_html_elements/11561_Sun.png",
            eventImgUrlType: "string",
            eventDate: 1580515200000,
            eventDateType: "int",
            eventPrice: "0",
            eventPriceType: "string",
            eventDescription: "Watch the sun eclipse from your balcony",
            eventDescriptionType: "string",
            eventTags: "",
            eventTagsType: "string",
            eventTickets: null,
            eventTicketsType: "null",
            showBar: true,
        }
    },
    {
        btnLabel: "Data with undefined error",
        eventData: {
            eventName: "Sun eclipse",
            eventNameType: "string",
            eventImgUrl: "https://solarsystem.nasa.gov/system/basic_html_elements/11561_Sun.png",
            eventImgUrlType: "string",
            eventDate: 1580515200000,
            eventDateType: "int",
            eventPrice: "",
            eventPriceType: "undefined",
            eventDescription: "Watch the sun eclipse from your balcony",
            eventDescriptionType: "string",
            eventTags: "",
            eventTagsType: "string",
            eventTickets: "2",
            eventTicketsType: "string",
            showBar: true,
        }
    }
]